### ISSUE TITLE
Test suite

### ISSUE THREAD

**Issue by Rich-Harris** [Rich-Harris/ramjet#1]
I have no idea what a good strategy for testing a library like this looks like...

**Comment by daviddahl** [comment]
You should perhaps try out "reftests": https://developer.mozilla.org/en-US/docs/Creating_reftest-based_unit_tests

**Comment by Rich-Harris** [comment]
Thanks, I wasn't aware of that. Could definitely come in handy. Reading around a bit though, reftests sound a bit hairy - lack of precise timing control, inconsistent approach to fuzzy matching... I'm inclined to put it on the 'one day' pile :)

In the meantime, I should probably close this issue - earlier today I added a basic [test.html](http://www.rich-harris.co.uk/ramjet/test.html) file ([source](https://github.com/Rich-Harris/ramjet/blob/master/demo/files/test.html)), which enables visual verification in any browser. Manual testing is a PITA but realistically I think it's the only option for now.
