### ISSUE TITLE
Artifacts in Firefor for Android

### ISSUE THREAD

**Issue by paldepind** [Rich-Harris/ramjet#17]
In Firefox for Android I every now an then get some pretty horrible artifact in the demo at the top of the Ramjet homepage.

The best description I can give is that the previous elements appears to do some kind of ghosting were it's not hidden properly.

**Comment by Rich-Harris** [comment]
Do the artifacts appear with any elements in particular? I'm wondering (hoping!) if it's the same bug as #6 - I've just tried Firefox 37 on Android 5 and it seems to work okay apart from that, so hopefully it isn't some impossible-to-reproduce Heisenbug

**Comment by Rich-Harris** [comment]
(sorry, should have been clearer - the SVG bug is the one that appears when scrolling during a transition into/out of the purple box on the homepage)

**Comment by paldepind** [comment]
It seems to be impossible for me to reproduce the artifacts I saw, today. I think you can close this :)

**Comment by moimael** [comment]
I can reproduce every time on last Firefox desktop release (47.0). Here is a screencast of the issue : 
[screencast here](https://vid.me/ve9A)
