### ISSUE TITLE
ui-view / angular-ui-router

### ISSUE THREAD

**Issue by fisch0920** [Rich-Harris/ramjet#26]
[feature request]

Would be awesome to have an angular directive which incorporates ramjet into angular-ui-router's ui-view s.t. state transitions could optionally include morphing.

**Comment by brandonramsey** [comment]
In case you didn't see it already, it looks like ngAnimate 1.4 basically does this with the ng-animate-ref feature.

**Comment by rbenjamint** [comment]
Can you post a code-sample? would help us a lot! Tnx anyway

**Comment by sithmel** [comment]
not really a ramjet issue here .... if someone is willing to wrap ramjet in an angularjs directive is more than welcome!
