### ISSUE TITLE
Support Jquery Selectors

### ISSUE THREAD

**Issue by MrAlexLau** [Rich-Harris/ramjet#32]
Would be convenient to say:
```
ramjet.transform( $('#a'), $('#b') );
```

instead of currently having to verbosely convert jquery elements to their corresponding dom elements:
```
ramjet.transform( $('#a').get(0), $('#b').get(0) );
```

**Comment by sithmel** [comment]
I do love using jQuery but I don't think this is a good idea. Why instead do you create a jQuery plugin for using ramjet in that context ? Something like:

    $('#a').ramjetTransform({to: $('#b')});

**Comment by MrAlexLau** [comment]
@sithmel - yes I like your idea better. What I originally proposed could easily become a leaky abstraction.
