### ISSUE TITLE
Uncaught TypeError: e.getBoundingClientRect is not a function

### ISSUE THREAD

**Issue by Danjavia** [Rich-Harris/ramjet#42]
Occur when i try to run
    ramjet.transform( a, b );

**Comment by electerious** [comment]
Same problem for me.

Error:
```js
TypeError: null is not an object (evaluating 'offsetParent.getBoundingClientRect')
```

Code:
```
let ramjet = require('ramjet'),
     $      = require('jquery')

ramjet.transform($item.get(0), $('.fixedBasket').get(0))
```

**Comment by bfred-it** [comment]
@electerious that might be because the element you selected doesn't have a parent, which means make sure you append the element to the page first.

**Comment by electerious** [comment]
@bfred-it The element is already on the page and has a parent.

Transforming to `.fixedBasket__badge` works fine.

![rentastic](https://cloud.githubusercontent.com/assets/499088/9980399/6c8fa5b6-5f98-11e5-89b4-01d8c3e3fbde.png)

**Comment by sithmel** [comment]
Can you please test if this is happening with the current master? it remember to have fixed it...

**Comment by electerious** [comment]
The code has changed. Can't reproduce it anymore, sorry. I guess it had something to do with `position: fixed` of the `fixedBasket`-element.

**Comment by sithmel** [comment]
Don't worry! I was not sure to have fixed it ;-)
