### ISSUE TITLE
Ignore certain CSS properties?

### ISSUE THREAD

**Issue by mrmartineau** [Rich-Harris/ramjet#53]
I would like to ignore `opacity` when using ramjet, is this possible? The reason is that i am fading in the target element when ramjet is triggered, because of this, ramjet correctly transitions the position to the correct place, but the opacity to `0`. Does that make sense?

**Comment by Rich-Harris** [comment]
It sounds like your best bet is probably to set the opacity of the target element to 1, run ramjet, set opacity back to 0, *then* fade in:

```js
target.style.opacity = 1;
ramjet.transform(source, target, {...});
target.style.opacity = 0;

fadeIn(target);
```

**Comment by mrmartineau** [comment]
thanks @Rich-Harris. it looks better now.
