### ISSUE TITLE
Transitions to/from SVG elements get borked during scroll...

### ISSUE THREAD

**Issue by Rich-Harris** [Rich-Harris/ramjet#6]
...because we're using `position: fixed` (for the main SVG element). Should probably invalidate-and-recalculate on scroll events for those cases.

**Comment by Merri** [comment]
I managed to get into state where I have two animations happening one after the another while scrolling during transition from SVG element to another; as if there were two of the same animations running.

Another issue I've noticed that the animation may suddenly go at double speed after scrolling during SVG element transition, which seems like a slightly different issue.

All this happened on the ramjet homepage and on Firefox.

**Comment by sithmel** [comment]
position: fixed issue is fixed
